### ISSUE TITLE
MWAA::Environment fails to create: "#/SourceBucketArn: failed validation constraint for keyword [pattern]"

### ISSUE THREAD

**Issue by nigelellis** [aws-cloudformation/aws-cloudformation-resource-schema#114]
Hi,

I'm trying to create an MWAA Environment resource via. CloudFormation.   When attempting to create the stack I receive an error:
> Error: **ROLLBACK_COMPLETE**: ["The following resource(s) failed to create: [AirflowMWAA]. Rollback requested by user." "**Properties validation failed for resource AirflowMWAA with message:\n#/SourceBucketArn: failed validation constraint for keyword [pattern]**"]

Here's a snippet of my CF stack:
```cloudformation
Description: airflow-head
Resources:
  AirflowMWAA:
    Type: AWS::MWAA::Environment
    Properties:
      ...
      SourceBucketArn: arn:aws:s3:::my-bucket-name
      ...
    DeletionPolicy: Delete
```

The bucket ARN is valid and is accepted if I create the env via. the MWAA wizard in the AWS console.  
How can I fix this?   The error is too terse to be useful.

Thanks,
Nigel.

**Comment by PatMyron** [comment]
[Those messages are definitely currently difficult to interpret](https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-cloudformation/issues/17) without looking at the [resource schema](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resource-type-schemas.html) itself:

```json
      "minLength": 1,
      "maxLength": 1224,
      "pattern": "^arn:aws(-[a-z]+)?:s3:::airflow-[a-z0-9.\\-]+$"
```

but it looks like the bucket name needs to start with `airflow`

**Comment by nigelellis** [comment]
@PatMyron thank you!   I'll give that a try.
