### ISSUE TITLE
Improve error message for pattern mismatch

### ISSUE THREAD

**Issue by rajashekargoudk** [aws-cloudformation/aws-cloudformation-resource-schema#85]
Currently, schema validation error for pattern mismatch returns  error in the form `"#/StringProperty: failed validation constraint for keyword [pattern]".` It would be good to include pattern value in the error message.

**Comment by PatMyron** [comment]
Agreed, adding this to https://github.com/aws-cloudformation/aws-cloudformation-resource-schema/issues/38
