### ISSUE TITLE
Resource's schema description

### ISSUE THREAD

**Issue by miparnisari** [aws-cloudformation/aws-cloudformation-resource-schema#97]
https://github.com/aws-cloudformation/aws-cloudformation-resource-schema/blob/1fd31cdb3ca76f8418c0209753e204e4e12c019a/src/main/resources/examples/resource/initech.tps.report.v1.json#L3

The description in the schema is being used in the Console UI, and this has led to very poorly named descriptions

![image](https://user-images.githubusercontent.com/5374887/82956018-c5111b00-9f64-11ea-852a-b693aa77a487.png)

https://github.com/search?q=%22Resource+schema+for%22+org%3Aaws-cloudformation&type=Code

**Comment by PatMyron** [comment]
This is called out:
https://github.com/aws-cloudformation/aws-cloudformation-resource-schema/blob/1e99ac138807111f16c5368cf6977ec09dbd6d42/src/main/resources/schema/provider.definition.schema.v1.json#L278

but maybe the console needs to be re-thought or `description` shouldn't be required:

https://github.com/aws-cloudformation/aws-cloudformation-resource-schema/blob/1e99ac138807111f16c5368cf6977ec09dbd6d42/src/main/resources/schema/provider.definition.schema.v1.json#L409-L412

based on how non-descriptive the descriptions have been so far
